POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "this a new note",
  "userId": "62df2b9a9fe6d70c04a73d73"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "random note",
  "important": true
}